//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKhachSan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class doanhthu
    {
        public string LoaiPhong { get; set; }
        public Nullable<System.DateTime> Thang { get; set; }
        public Nullable<float> DoanhThu1 { get; set; }
    
        public virtual loaiphong loaiphong1 { get; set; }
    }
}
